from __future__ import annotations

DATE_NUMBER_FORMAT_IDS = {
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    27,
    30,
    36,
    45,
    46,
    47,
    50,
    57,
}

FIELD_ALIASES = {
    "change_type": {
        "changetype",
        "change",
        "actiontype",
        "action",
    },
    "statement_type": {
        "statementtype",
        "statement",
    },
    "changed_value": {
        "value",
        "changedvalue",
        "field",
    },
    "from_value": {
        "from",
        "fromvalue",
        "oldvalue",
    },
    "to_value": {
        "to",
        "tovalue",
        "newvalue",
    },
    "event_time": {
        "eventtime",
        "timestamp",
        "datetime",
        "eventdatetime",
        "time",
        "createdat",
        "updatedat",
        "eventdate",
        "date",
    },
    "actor_type": {
        "actortype",
        "typeactor",
        "bytype",
        "updatedbytype",
        "usertype",
    },
    "actor_name": {
        "actor",
        "actorname",
        "username",
        "user",
        "updatedby",
        "owner",
        "operator",
    },
    "from_status": {
        "fromstatus",
        "oldstatus",
        "previousstatus",
        "statusfrom",
        "statusbefore",
        "from",
    },
    "to_status": {
        "tostatus",
        "newstatus",
        "status",
        "statusto",
        "statusafter",
        "to",
    },
    "document_id": {
        "documentid",
        "docid",
        "caseid",
        "fileid",
        "requestid",
        "recordid",
        "document",
        "workflowid",
    },
    "action_type": {
        "action",
        "activity",
        "event",
        "operation",
        "eventtype",
        "detail",
        "description",
        "actiontype",
    },
    "submitted_for_reanalysis": {
        "submittedforreanalysis",
        "reanalysis",
        "isrework",
        "reworkflag",
        "submitted_for_reanalysis",
    },
    "auto_closed": {
        "autoclosed",
        "autoclose",
        "isautoclosed",
        "autotimeout",
        "auto_timeout",
    },
    "timeout_minutes": {
        "timeoutminutes",
        "sessiontimeoutminutes",
        "timeoutconfigminutes",
        "timeout",
    },
}

CSV_DECODE_CANDIDATES = (
    "utf-8-sig",
    "utf-8",
    "utf-16",
    "utf-16-le",
    "utf-16-be",
    "cp874",
    "tis-620",
    "cp1252",
)
MOJIBAKE_MARKERS = (
    "\u00c3",
    "\u00c2",
    "\u00e0\u00b8",
    "\u00e0\u00b9",
    "\u00e1\u00bb",
    "\u00e1\u00ba",
    "\u00ef\u00bb\u00bf",
)
